// <auto-generated />
using BryankroesbeekNl.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BryankroesbeekNl.Migrations
{
    [DbContext(typeof(BryankroesbeekNlContext))]
    partial class BryankroesbeekNlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("BryankroesbeekNl.Models.Database.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("GithubId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Position")
                        .HasColumnType("int(11)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit(1)");

                    b.HasKey("Id");

                    b.ToTable("Repository");
                });
#pragma warning restore 612, 618
        }
    }
}
