// <auto-generated />
using BryankroesbeekNl.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace BryankroesbeekNl.Migrations
{
    [DbContext(typeof(databaseContext))]
    partial class databaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");
#pragma warning restore 612, 618
            modelBuilder.Entity("BryankroesbeekNl.Models.InfoBlock", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd();
                    b.Property<string>("Title");
                    b.Property<string>("Content");
                    b.Property<DateTime>("CreatedDate");
                    b.Property<DateTime>("UpdatedDate");
                });
        }
    }
}
